### ISSUE TITLE
Passing  Grafana changed variables to the plugin

### ISSUE THREAD

**Issue by fercasjr** [VolkovLabs/volkovlabs-form-panel#158] opened 2023-04-18 16:57 UTC
So far, this plugin has been great for me to interface with InfluxDB. The only caveat is that if I have a dashboard which has a drop-down menu for selecting variables (Grafana variable) on change It doesn't trigger the initial request.

I can use that variable on the query and then use the query results to make a dynamic form. 👌
the problem is that since the plugin makes the initial request just on loading, refreshing, or after updating the request. I cannot get the updated query result just after selecting a new variable from the drop-down menu.

I need to select the Grafana variable, then use the reset button in the plugin or refresh the page to update the query results and my dynamic forms. the funny thing is on Grafana the query itself if updated automatically so if I am using the "table view" I can see the query results change but I cannot pass those new values to the plugin.

maybe there is a way to do it, but I didn't find the specifics in the documentation.

other than that great work guys!!

**Comment by mikhail-vl** [comment] 2023-04-18 17:19
@fercasjr Thank you. The panel updates only when loaded or refresh happens.

  If you update the Dashboard Variable and Data Source got updated, it's not triggering the form refresh as you noticed.
  It's easy to fix. I will update in the upcoming version.

**Comment by mikhail-vl** [comment] 2023-09-09 20:13
@fercasjr The issue is fixed in 3.2.1. I can update the variable, and the initial request will return new data from Query or Data Source.

![Screenshot 2023-09-09 at 16 11 26](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/47795110/3c086e0b-6974-4674-871b-e2f64ef05f59)

Please test and let us know if there is anything else.

**Closed by mikhail-vl** 2023-09-09 20:13 UTC
Labels: question

**Comment by fercasjr** [comment] 2023-09-18 20:06
Hi @mikhail-vl again awesome job.

I am a little confused about this "fix" / "new feature".  

I am trying to test this, but I got the same result, I selected a different value for the variable, and then I have this simple line to see the result:

`console.log(data.series.find((serie) => serie.refId === "A").fields.find((f) => f.name === "STATE").values.buffer[0])`

the output does not update.... at least not from the Grafana query itself.

however, if I choose to use "Data Source" as the Initial request and create a query that way then I get the updated output each time I select a different value for the variable (which Is the desired behavior).

`console.log(dataQuery.data[0].fields[3].values.buffer[0]);`

In this picture I toggled between 2 known states and as you can see using Grafana query got stuck on same value

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/122648641/0ec90b9e-712e-48b7-bc11-f5fd919129ab)

I saw also this note on your blog posts:

![image](https://github.com/VolkovLabs/volkovlabs-form-panel/assets/122648641/d830b4c3-97c7-40aa-923b-a0b81c009f7c)
 
and I am not sure if this is what you mean by that.

Don't get me wrong. I can work with this; however complex queries will be a little bit difficult to parse and trouble shoot with the scaped characters and also Grafana's transformations can't be used that way (I don't need it but it's nice to have). 

There is always the chance that I am doing something wrong, and that is why I am asking.

**Comment by Evgeny243** [comment] 2023-10-12 15:27
@fercasjr I am trying to get the plugin work and would greatly appreciate your help! I am as much a "beginner" as one can be. 

I want to load data from Influxdb and write to it. First, I tried the "Query" option and then the Form Element is being updated by the usual way (from the left-bottom part of Grafana). When I try to place your example into the Initial Request/Custom Code, and choose other options (--, Data Source, Get) - this code does not generate anything.  
I use following Custom Code inside Initial Request:
**************************************
const query = `
from(bucket: "bucket1")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "analog_io")
  |> filter(fn: (r) => r["_field"] == "PD voltage")
  |> last()
`;

const url = `http://influxdb...../orgs/..../`;

const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/vnd.flux",
    Accept: "application/csv",
    Authorization: "bla-bla-bla - token code",
  },
  body: query,
})
  .catch ((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });
**************************************

Thank you!

**Comment by fercasjr** [comment] 2023-10-12 17:49
@Evgeny243  this should work:
 as it is in the example on the documentation (which I made and referenced myself may times because I always forget how to do it), dont forguet the `` to encapsulate the query
https://volkovlabs.io/plugins/volkovlabs-form-panel/servers/influx/

const query = `
from(bucket: "bucket1") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r["_measurement"] == "analog_io") |> filter(fn: (r) => r["_field"] == "PD voltage") |> last()
`;

/**
 * Set URL
 */
const url = `http://influxdb...../orgs/..../`;

/**
 * Fetch
 */
const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/vnd.flux",
    Accept: "application/csv",
    Authorization: "Token INFLUX_API_TOKEN",
  },
  body: query,
})
  .catch((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });

**Comment by fercasjr** [comment] 2023-10-12 18:13
The first one [ - ]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Evgeny243** [comment] 2023-10-12 19:42
still no luck...

**Comment by mikhail-vl** [comment] 2023-10-17 20:33
@Evgeny243 Have you seen the video https://www.youtube.com/watch?v=hVy9NfFiI5U? It's explain the difference between REST API, Data Source and Query.

  We also have a series of blog post and releases I suggest to review: https://volkovlabs.io/blog/tags/data-manipulation/.

**Comment by mikhail-vl** [comment] 2023-10-17 20:34
@fercasjr If it's still an issue, could you please open a new issue for tracking and we will take a closer look.

**Comment by Evgeny243** [comment] 2023-10-17 21:00
@mikhail-vl thanks, I've seen it. But still it is quite confusing for me. Now that I can see the console I hope the progress will go faster.
